on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
          TOKEN: ${{  secrets.TOKEN  }}
      - name: Run script
        run: |
          python main.py
