on:
    workflow_dispatch:

env:
  SOME_VAR: $${{  secrets.TOKEN  }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: Run script
        run: |
          python main.py
