on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{secrets.TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
      - name: Run script
        run: |
          # main.pyの実行
          python main.py
